[Traits] Clarify canonical use of version related traits
OpenAssetIO/OpenAssetIO-MediaCreation pull request #54
Opened 2023-08-14 08:42 UTC by foundrytom

The choice for reverse chronological comes from common use patterns.

2023-08-14 09:06 UTC, feltech requested changes
Nice little clarification.

2023-08-14 13:07 UTC, foundrytom commented on traits.yml
> +          is usually reverse chronological order, but dynamic version
lols, yes, sorry I thought Id finished that.

2023-08-14 13:10 UTC, foundrytom commented on traits.yml
> +          is usually reverse chronological order, but dynamic version
[Cough...](https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/pull/54/commits/303adb629221d6779b12f84a798f45ad69f45aee) sorry about that. Brain not functioning so not sure if that is in any way reasonable english...

2023-08-14 13:44 UTC, elliotcmorris approved these changes

2023-08-14 16:28 UTC, feltech commented on traits.yml
> +          is usually reverse chronological order, but dynamic version
[question] By dynamic versions potentially appearing in other locations, are you thinking like "approved", which might not be the most recent version, but would still be at the top of the list?

Perhaps just stopping at "This is usually reverse chronological order" is sufficient.

2023-08-14 17:19 UTC, foundrytom commented on traits.yml
> +          is usually reverse chronological order, but dynamic version
Yeah, thats what I was thinking. Ill keep it simple 👍

2023-08-15 10:19 UTC, foundrytom commented on traits.yml
> +          is usually reverse chronological order, but dynamic version
Simplified [here](https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/pull/54/commits/af1c6df6a5168983d99c0d100a18e56be62e7114)

2023-08-15 10:19 UTC, foundrytom commented on traits.yml
> +              set to a tag that produces equivalent behaviour.
Elaborated [here](https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/pull/54/commits/85243ea2f7706bd2fbf99da50c509ff53117adf6).

2023-08-15 10:28 UTC, feltech approved these changes
:+1:

2023-08-15 11:11 UTC, merged